services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - postgres

  db:
    build:
      context: ./build/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db
    # Acess the database with the following command:
    # docker compose exec -it db psql -h localhost -p 5432 -U postgres

volumes:
  db:
networks:
  db: